import os
from unittest.mock import patch
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def test_full_workflow_integration():
    """
    Tests the entire FastAPI + LangGraph integration end-to-end.
    We force the LLM_PROVIDER to 'unknown' to ensure the mock logic inside the agents
    runs, allowing us to test the graph traversal without hitting real LLM APIs.
    """
    with patch.dict(os.environ, {"LLM_PROVIDER": "unknown", "LINEAR_API_KEY": ""}, clear=True):
        # 1. Trigger the webhook
        ticket_payload = {
            "title": "Integration Test Ticket",
            "description": "This is an end-to-end integration test."
        }
        response = client.post("/webhook/ticket", json=ticket_payload)
        
        assert response.status_code == 200
        data = response.json()
        assert data["message"] == "Workflow started"
        
        thread_id = data["thread_id"]
        
        # 2. Check the status after the synchronous graph execution
        # Because we're not hitting real APIs, the mock logic runs instantly and the graph
        # should have completed its execution all the way to the end.
        status_response = client.get(f"/workflow/{thread_id}/status")
        assert status_response.status_code == 200
        status_data = status_response.json()
        
        # The graph should have finished, meaning there is no 'next_node' pending.
        # (It doesn't pause at human_input because our mock logic didn't set needs_human_input to True)
        assert status_data["next_node"] == []
        
        # 3. Verify the final state values generated by the LangGraph agents
        state_values = status_data["state_values"]
        
        # Verify PO Agent created Use Case tickets
        assert "use_case_tickets" in state_values
        assert len(state_values["use_case_tickets"]) > 0
        
        # Verify Dev Lead Agent created Dev Tickets
        assert "dev_tickets" in state_values
        assert len(state_values["dev_tickets"]) > 0
        
        # Verify the DevOps and Developer agents processed the tickets
        dev_tickets = state_values["dev_tickets"]
        for ticket in dev_tickets:
            assert ticket["status"] == "DONE"
            
        # Verify messages from the agents were appended to the state
        messages = state_values["messages"]
        assert len(messages) > 0
